# Generated by Django 5.0.6 on 2024-06-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
