# Generated by Django 5.0.6 on 2024-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBulkUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now=True)),
                ("csv_file", models.FileField(upload_to="company/bulkupload/")),
            ],
        ),
    ]
